### PR TITLE
Update kopia version to 1e98511

### PR DESCRIPTION
**Pull request by redgoat650**
## Change Overview

See https://github.com/kopia/kopia/commit/1e98511c2ea07fbcfbe4cf0f29b58900bb32e460

This PR updates the binary version in the `kanister-tools` image and the module version. It also updates the `golangci-lint` version in the build image and updates the build image to `v0.0.31`.

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [x] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test

## Issues 

- fixes #issue-number

## Test Plan

- [x] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

**Comment by redgoat650** [comment]
Adding `hold off merging` to sort out the `govulncheck` warnings

**Review by julio-lopez — APPROVED** [review]
LGTM  ✅
🥇Thanks for doing this.

**Comment by julio-lopez** [comment]
@redgoat650 Not merging since you added the `hold off merging` label. Feel free to merge (while it is still up to date 😉 )

**Comment by redgoat650** [comment]
I think we'll have to postpone the kopia update, now that we've reverted the gRPC changes due to ipv6 issues. I'll close this ticket and reopen once the needed kopia fixes are in place.

https://github.com/kanisterio/kanister/pull/2849

**Pull request closed without merging**
