### PR TITLE
Add GH Actions CI Workflow

### PR DESCRIPTION
**Pull request by ihcsim**
## Change Overview

This PR re-enables the GH Actions CI workflow. I would like to let it run in parallel to the current CI setup to compare the two CI solutions in terms of their speed, efficiency, responsiveness, flakiness and cost.

All the existing Travis CI jobs and stages have been added to the GH Actions `main.yaml` workflow. A completed successful CI run looks like this:

github-actions-ci

See https://github.com/kanisterio/kanister/actions/runs/2097423926.

Some highlights include:

* Parallel, independent jobs to run the `test`, `integration-test`, and `helm-test` suites
* Parallel, independent jobs to build the `controller`, `kanctl` and `kando` binaries
* Independent k3d clusters to run the test suites
* Run the `release` job only when there is a new merge into `master` or a new tag
* Takes about 25 minutes to complete compared to at least 30 mins on Travis (excluding the `make release-snapshot` target)
* Test flakes happen less frequently with the k3d setup

## Pull request type

Please check the type of change your PR introduces:
- CI/CD

## Issues

- Previously https://github.com/kanisterio/kanister/pull/917, https://github.com/kanisterio/kanister/pull/894

### CODE REVIEW

**Review by viveksinghggits — APPROVED** [review]
Like we discussed we should let it run parallel to travis for sometime.

**Comment by ihcsim** [comment]
@pavannd1 yes, but it should be idempotent.

**Review by julio-lopez — COMMENTED** [review]
🎉 🎊 🚀 🥳
🥇Thanks for doing this.

In future iterations it'd be good to explore how to break down the jobs into smaller pieces, and also increase the level of parallelism. Also, it'd be good to figure out how long does it take to pass artifacts between jobs (accounting for both upload & download) and see whether or not that provides benefits vs. for example, re-running some steps.

Another thing to consider later is whether it makes sense to have the release job in a separate workflow.

**Comment by julio-lopez** [comment]
> Like we discussed we should let it run parallel to travis for sometime.

It'd make sense to merge it then and have it be a "not required" check.

**Comment by ihcsim** [comment]
Looks like mergify requires addition `workflow` permission to merge this.

**Pull request merged**
