### PR TITLE
Group `check.v1` package with third-party package

### LINKED ISSUE #3136: Group `check.v1` package with third-party package.
**Is your feature request related to a problem? Please describe.**
while enabling the `gci` linter in this [PR]()https://github.com/kanisterio/kanister/pull/3094
- `check.v1` should NOT be in a separate "group".
- `check.v1` is a third-party package. The import statements should be grouped in 3 groups.
   -  standard library imports
   - third-party packages
   - project local packages, that is those that are defined in the same module / project.

**Describe the solution you'd like**
-  Remove the `.` from `. "gopkg.in/check.v1"` and then group it with third-party package . Use `check` prefix when you are  gettting issue after removing `.`

### PR DESCRIPTION
**Pull request by anishbista60**
## Change Overview

-  Remove the `.` from `. "gopkg.in/check.v1"` and then group it with third-party package . Use `check` prefix when you are  gettting issue after removing `.`

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test
- [ ] :building_construction: Build

## Issues 

- fixes #3136

## Test Plan

- [ ] :muscle: Manual
- [x] :zap: Unit test
- Enable `gci` linter  and remove the `dot` which is present  under `gci.sections` in `.golangci.yml` (Just to check that whether gci throwing error or not, which will not be included as a part of this PR) 
- Then, Run `make golint` for testing. 
- [ ] :green_heart: E2E

### CODE REVIEW

**Comment by anishbista60** [comment]
@viveksinghggits Please take a look once. So,  i can move forward

**Comment by viveksinghggits** [comment]
> @viveksinghggits Please take a look once. So, i can move forward. #3094

can you please add the test plan for the PR @anishbista60 .

**Comment by anishbista60** [comment]
@viveksinghggits sure i'll do it but the changes are not completed yet. 
could you please verify the changes ? if it's looks good then i can move forward for other files.

**Comment by viveksinghggits** [comment]
@anishbista60 yes the current changes look good.

**Comment by anishbista60** [comment]
@viveksinghggits Everything Done. Please ! have a look.  Works fine in my machine. 
Screenshot from 2024-09-19 18-39-34

**Comment by julio-lopez** [comment]
For future reference, it makes sense to split large changes like this where 100s of files are modified with the same type of change. For example, instead o single large PR, have individual PRs with say 20 files per PR. That makes them easier to review individually, and also merge, as it reduces the probability of conflicts, and if there are conflicts, then other non-conflicting PRs can be merged.

**Review by julio-lopez — APPROVED** [review]

**Comment by julio-lopez** [comment]
@anishbista60 
🥇Thanks for doing this.

🎉 🎊 🚀 🥳

**Comment by anishbista60** [comment]
> @anishbista60 For future reference, it makes sense to split large changes like this where 100s of files are modified with the same type of change. For example, instead o single large PR, have individual PRs with say 20 files per PR. That makes them easier to review individually, and also merge, as it reduces the probability of conflicts, and if there are conflicts, then other non-conflicting PRs can be merged.

Sure , ok.

**Comment by pavannd1** [comment]
@anishbista60 Please verify all the checks in this PR to ensure we haven't flipped anything. I found one issue causing test failures [here](https://github.com/kanisterio/kanister/pull/3137/files#diff-6308bb49b562ea685d456c02f84de0c391ec6da2c88d19b07fe9f161f322c62cL110).

One of the reasons to break down large PRs into multiple smaller PRs - it'll be easier for reviewers to catch such issues.

**Comment by anishbista60** [comment]
@pavannd1 Sorry ! for difficulty while reviewing and obviously going to 100 of files would be difficult. I walked though entire changes and doesn't get anything except yours ones.

**Comment by anishbista60** [comment]
By the next time it will never happen.

**Pull request merged**
