### PR TITLE
Deprecate unused Helm releases

### PR DESCRIPTION
**Pull request by rahulchheda**
Signed-off-by: Rahul M Chheda <rchheda@infracloud.io>

## Change Overview

- Removed all the unused Helm Charts
- Changed location of DockerFiles
- Verified all changes via this commit: https://github.com/kanisterio/kanister/pull/719/commits/a636767313b6b33d0a6e853bbdbb8e2482b16b9e
- Deprecated Push for un-used Helm charts

Please check the commit wise descriptions for more overview.

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [x] :robot: Test

## Issues

- #XXX

## Test Plan

- [ ] :muscle: Manual
- [ ] :zap: Unit test
- [x] :green_heart: E2E

### CODE REVIEW

**Comment by rahulchheda** [comment]
> Whats up with the licenses file?

It came up when I ran the integration test, should I remove it?

**Comment by viveksinghggits** [comment]
I am not sure why integration test created that file, it shouldnt. Yes, I think we should remove that file.

**Comment by rahulchheda** [comment]
> I am not sure why integration test created that file, it shouldnt. Yes, I think we should remove that file.

Done @viveksinghggits

**Comment by viveksinghggits** [comment]
LGTM

**Pull request merged**
