### PR TITLE
Update error to log backup output in case of failure

### PR DESCRIPTION
**Pull request by DeepikaDixit**
## Change Overview

Update error to log backup output in case of failure

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [X] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test

## Issues

None filed 

## Test Plan

- [ ] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

**Comment by vkamra** [comment]
@DeepikaDixit - I know I asked for this but can you paste the output of what stdout typically looks like on this job? I want to see what this will do to our logs. Also we should use a log field rather than infof

**Comment by DeepikaDixit** [comment]
> @DeepikaDixit - I know I asked for this but can you paste the output of what stdout typically looks like on this job? I want to see what this will do to our logs. Also we should use a log field rather than infof

@vkamra sure

**Comment by DeepikaDixit** [comment]
> @DeepikaDixit - I know I asked for this but can you paste the output of what stdout typically looks like on this job? I want to see what this will do to our logs. Also we should use a log field rather than infof

@vkamra we are logging `stdout` here: https://github.com/kanisterio/kanister/blob/4be0d48fe66151014ffdb99bcd59f61ae689817c/pkg/function/backup_data.go#L152

**Comment by DeepikaDixit** [comment]
@vkamra 

This is the output for:

`log.Info().Print(stdout) `
```
created new cache in /root/.cache/restic

Files:           1 new,     0 changed,     0 unmodified
Dirs:            2 new,     0 changed,     0 unmodified
Added to the repo: 1.056 KiB

processed 1 files, 0 B in 0:00

**Pull request merged**
