### PR TITLE
Add the `spec.selector` field in the time-logger deployment

### LINKED ISSUE #3120: Missing `spec.selector` field in  `time-logger` deployment manifest example in kanister new documentation
**Is your feature request related to a problem? Please describe.**
- [time-logger](https://docs-new.kanister.io/tutorial.html) deployment doesnot have `spec.selector` field.

**Describe the solution you'd like**
-  Add the missing field.

### PR DESCRIPTION
**Pull request by anishbista60**
## Change Overview

Added the `spec.selector` field in the time-logger deployment example in kanister new deployment. 
## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test
- [ ] :building_construction: Build

## Issues 

- fixes #3120 

## Test Plan

- [ ] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

**Comment by anishbista60** [comment]
@shuguet could you please take a look here ?

**Comment by PrasadG193** [comment]
Looks good, thanks for fixing this

**Review by PrasadG193 — APPROVED** [review]

**Comment by anishbista60** [comment]
@PrasadG193 do you have right to merge it ?

**Comment by anishbista60** [comment]
mergify doesn't have enough permission.

**Pull request merged**
