### PR TITLE
Use Networking/v1 as default group version in ingress manager

### PR DESCRIPTION
**Pull request by PrasadG193**
## Change Overview

This PR removes the Discovery APIs from ingress manager.
Now it uses networking v1 as default group version to manager ingress resources.

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [x] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [x] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test

## Issues 

- fixes #issue-number

## Test Plan

- [x] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

**Review by onkarbhat — APPROVED** [review]
LGTM 👍🏼

**Review by pavannd1 — COMMENTED** [review]
Note for the future: Not sure if we still need the `IngressManager`. We could probably use `NetworkingV1` directly everywhere.

**Review by viveksinghggits — APPROVED** [review]

**Comment by viveksinghggits** [comment]
Nit: Should we remove `IsResAvailableInGroupVersion` from `discover.go`?

**Comment by pavannd1** [comment]
Merging this now. Let's follow-up on the two comments soon.

**Pull request merged**
