### PR TITLE
Update kopia commit in kanister-tools image to latest master

### PR DESCRIPTION
**Pull request by KastenMike**
Bumping since it was last done 6 months ago and kopia uses newer azure APIs since then

### CODE REVIEW

**Review by PrasadG193 — APPROVED** [review]

**Review by pavannd1 — CHANGES_REQUESTED** [review]
Holding off until all the downstream tests are complete

**Review by ankitjain235 — CHANGES_REQUESTED** [review]
We should also update Kopia dependency version in go.mod so that both CLI and SDK are in sync.

**Comment by KastenMike** [comment]
> We should also update Kopia dependency version in go.mod so that both CLI and SDK are in sync.

What do you mean? This PR is to uptake the go.mod changes or I'm misunderstanding

**Comment by KastenMike** [comment]
Closing and trying to create directly in kanister repo

**Pull request closed without merging**
