### PR TITLE
Adjust the installation command

### LINKED ISSUE #3118: Adjustment in Installation command in `kanister new-docs`
**Is your feature request related to a problem? Please describe.**
- I try to copy paste the command for  kanister operator installation from [newdocs](https://docs-new.kanister.io/install.html).
-  The first command `helm repo add kanister <https://charts.kanister.io/>` throws error 
```
bash: syntax error near unexpected token `newline'
```
- While second command shows 
```
anishbista@anishbista-RedmiBook-15-Pro:~$ helm -n kanister upgrade \--install kanister \--create-namespace
kanister/kanister-operator
Error: "helm upgrade" requires 2 arguments

Usage:  helm upgrade [RELEASE] [CHART] [flags]
bash: kanister/kanister-operator: No such file or directory
```
- And so on. 

**Describe the solution you'd like**
-  Provide the  commands in proper format  so that folks won't  have to fix it again.

### PR DESCRIPTION
**Pull request by anishbista60**
## Change Overview

Made some changes to installation in `kanister new-docs`
## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test
- [ ] :building_construction: Build

## Issues 

- fixes #3118 3118

## Test Plan

- [x] :muscle: **Manual Testing:**
   - Navigated to the `docs_new` directory.
   - Installed necessary dependencies using `npm install`.
   - Installed VitePress with `npm install vitepress`
   - Ran the development server with `npm run docs:dev` and verified that the documentation site loaded successfully without errors and changes are being rendered properly. 
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

**Comment by anishbista60** [comment]
@PrasadG193 would you mind to take a look here ?

**Comment by PrasadG193** [comment]
Can you please share the test plan - how did you test and verified the changes? In this case, can you please attach a screenshot of the rendered page after your changes?

**Comment by anishbista60** [comment]
> Can you please share the test plan - how did you test and verified the changes? In this case, can you please attach a screenshot of the rendered page after your changes?

anish

**Comment by anishbista60** [comment]
> Can you please share the test plan - how did you test and verified the changes? In this case, can you please attach a screenshot of the rendered page after your changes?

Screenshot from 2024-09-16 11-43-46

**Comment by PrasadG193** [comment]
@anishbista60 I think I wasn't clear with my comment.
I meant how did you test and validate the documentation changes you have made in this PR. Did you build and docs and verified if the changes are rendered correctly on the built html page. Can you add a screenshot of that?

**Comment by anishbista60** [comment]
@PrasadG193 looks fine in my local server. 

Screenshot from 2024-09-16 12-54-24
Screenshot from 2024-09-16 12-54-49
Screenshot from 2024-09-16 12-55-28

**Comment by PrasadG193** [comment]
Thank you, can you please update the Test plan section in the PR description with your testing details?

**Comment by anishbista60** [comment]
@PrasadG193 Done looks fine . Thank you.

**Review by PrasadG193 — APPROVED** [review]
LGTM, thank you for fixing this

**Comment by anishbista60** [comment]
mergify doesn't have enough permission.

**Comment by anishbista60** [comment]
@julio-lopez could you  please try to get it merge ?

**Comment by anishbista60** [comment]
Any one here please try to get it merge.

**Comment by anishbista60** [comment]
@PrasadG193  could you please merge it ?

**Pull request merged**
