### PR TITLE
Use GithubActions instead of Travis CI for Kanister CI

### PR DESCRIPTION
**Pull request by chaitanya-baraskar**
## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [x] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test

## Test Plan
Ran complete CI on code on forked repo. It's working as expected.
https://github.com/chaitanya-baraskar/kanister/actions/runs/398736954

- [x] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

**Comment by pavannd1** [comment]
@TribalNightOwl The tests here should be similar to the tests we are running on Travis CI. Refer to `.travis.yml`

**Comment by chaitanya-baraskar** [comment]
@pavannd1 I think it's running all tests from travis. I just changed name for steps. Please let me know if I am missing any step here.

**Comment by TribalNightOwl** [comment]
Note that the GitHub actions is set up to trigger on the `main` branch.  This repo would need to be changed to use the `main` branch as the default instead of `master`.

**Comment by TribalNightOwl** [comment]
Go Linter:

If we are adopting `Jerome1337/golint-action@v1.0.2`

Should we remove the make target `golint`?

Also our `golint` target has more configuration settings:
`golangci-lint run --timeout ${TIMEOUT} --skip-dirs ${SKIP_DIR_REGEX} -E maligned,whitespace,gocognit,unparam -e '`ctx` is unused'`

than: https://github.com/Jerome1337/golint-action/blob/master/entrypoint.sh

`GOLINT_OUTPUT="$(golint -set_exit_status $1)"`

So maybe we should just call our `golint` target, or configure `Jerome1337/golint-action@v1.0.2` to use the same settings as our `golint` target.

**Comment by chaitanya-baraskar** [comment]
@TribalNightOwl sure. I will look into it.

**Review by TribalNightOwl — APPROVED** [review]
Note that the GitHub actions workflow is set up to trigger on the main branch.

This repo would need to be changed to use the main branch as the default instead of master.

**Comment by PrasadG193** [comment]
@chaitanya-baraskar the followup tasks would be 
- Remove .travis.yaml
- Update mergify config to switch github action checks from travis CI checks

**Review by PrasadG193 — APPROVED** [review]

**Comment by PrasadG193** [comment]
Has to be merged manually as there are changes in workflows.

**Comment by chaitanya-baraskar** [comment]
Creating new PR as this one is really messy. @TribalNightOwl @pavannd1 @PrasadG193

**Pull request closed without merging**
