### PR TITLE
Add arg to connect to kopia repos as readonly

### PR DESCRIPTION
**Pull request by adowair**
## Change Overview

This commit adds a new field to the repository and repository server connect arg structs to connect to a repository/server in read-only mode. As of https://github.com/kopia/kopia/pull/2799, there are new kopia workflows which require a read only connection.

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [x] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test

## Test Plan

- [ ] :muscle: Manual
- [x] :zap: Unit test
- [ ] :green_heart: E2E

```console
Running tool: /usr/local/bin/go test -timeout 30s -coverprofile=/var/folders/pz/vhp6gb9900x1hw1cmkcn74s40000gp/T/vscode-goLblpkp/go-code-cover -run ^Test$ github.com/kanisterio/kanister/pkg/kopia/command

ok  	github.com/kanisterio/kanister/pkg/kopia/command	1.019s	coverage: 87.0% of statements
```

### CODE REVIEW

**Comment by adowair** [comment]
@aaron-kasten kopia dependency in kanister needs to be bumped to https://github.com/kopia/kopia/pull/2799 (https://github.com/kopia/kopia/commit/c65613ccba2b2d74e95d890a914434ebb78489c0) for this PR to make sense. There are downstream dependencies blocked on this PR.

**Comment by adowair** [comment]
Closing for now, as it is possible to get around this downstream

**Review by ankitjain235 — COMMENTED** [review]
LGTM

**Comment by julio-lopez** [comment]
@ankitjain235 Can you drive merging this PR?

**Comment by ankitjain235** [comment]
@julio-lopez The Kopia commit we are referring to is after the one mentioned in the comment above. I don't see that PR needs any changes, and we can merge it as it is. cc @pavannd1

**Review by pavannd1 — APPROVED** [review]

**Pull request merged**
