### PR TITLE
Enable grpc for connecting to Kopia API Server

### PR DESCRIPTION
**Pull request by ankitjain235**
## Change Overview

This PR stops setting `DisableGRPC` to `true`, thus allowing Kopa API client to connect to server using GRPC.
Note: The kopia API server also needs to be started with GRPC enabled.

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test

## Issues

- #XXX

## Test Plan

- [ ] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

**Comment by ihcsim** [comment]
Is this merge-able? If not, please label it with `hold off merging`. IIRC, we had to revert this due to regression, right?

**Comment by pavannd1** [comment]
Looks like the downstream tests are passing for this change and the issue seen before is not reproducible. But unfortunately, we won't be able to completely say with confidence that it'll work until we release a new version of Kanister and let the tests run for a week or two without disruption.

**Comment by pavannd1** [comment]
We can hold off on this until we have a way to create Kopia server in Kanister 👍🏼

**Comment by pavannd1** [comment]
We can close this and follow-up later 👍🏼

**Pull request closed without merging**
