### PR TITLE
Add support to configure labels and annotations of the pods created by kanister functions

### PR DESCRIPTION
**Pull request by viveksinghggits**
## Change Overview

This PR introduces two new args `podLabels` and `podAnnotations` to the the Kanister functions that create new pods when they are executed.
This is docs PR that updates the relevant docs. https://github.com/kanisterio/kanister/pull/3014

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [x] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test
- [ ] :building_construction: Build

## Issues 

- fixes #issue-number

## Test Plan

- [x] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

//ToDo: Add tests unit or e2e.

### CODE REVIEW

**Comment by hairyhum** [comment]
I see there are other PRs related to this change. Can we have them in the same PR? There shouldn't be too much code to keep it reviewable and it's actually easier to review them all as one.

**Review by PrasadG193 — APPROVED** [review]
LGTM

**Comment by PrasadG193** [comment]
@viveksinghggits can you PR link to update docs here?

**Comment by viveksinghggits** [comment]
> @viveksinghggits can you PR link to update docs here?

I have added the link in PR desc.

**Pull request merged**
