### PR TITLE
PodOptions should take ImagePullSecrets

### PR DESCRIPTION
**Pull request by bathina2**
## Change Overview

This modification will enable PodOptions to take ImagePullSecrets as an input when creating a Pod.

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [x] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test

## Issues 

- fixes #issue-number

## Test Plan

- [ ] :muscle: Manual
- [x] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

**Comment by pavannd1** [comment]
CI error is unrelated. There was another PR to update the linters - let me merge that

**Comment by bathina2** [comment]
@pavannd1 May not be unrelated unless we are no longer checking gocognit? That test is a bit poorly written and has a lot of cases/complexity. Either way I added an ignore since its just a test

**Comment by pavannd1** [comment]
I had missed the actual error. Let's merge this 👍🏼

**Review by pavannd1 — APPROVED** [review]

**Comment by bathina2** [comment]
@pavannd1 Not merging yet because there are some other consequences, will discuss in slack.

**Pull request closed without merging**
