### PR TITLE
support tolerations and node Selector

### PR DESCRIPTION
**Pull request by fabiomarinetti**
## Change Overview

This Pull Request add the support for tolerations and nodeSelector of the kanister helm chart as per [issue 2707](https://github.com/kanisterio/kanister/issues/2707) request. I added the default empty values in the values.yaml file and added the logic for handling them in the deployment helm template.

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [x] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test

## Issues 

- fixes: [2707](https://github.com/kanisterio/kanister/issues/2707) 

## Test Plan

- [x] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

**Comment by viveksinghggits** [comment]
@fabiomarinetti can you please PR description and test plan in PR.

**Comment by fabiomarinetti** [comment]
@viveksinghggits I added a short description in the PR. What about helm chart test? I don't see where it is covered.

**Comment by viveksinghggits** [comment]
I think we should add something here https://github.com/kanisterio/kanister/blob/master/pkg/testing/helm/helm_test.go
Basically we should be able to install (or dry-run) the local helm chart by setting taints and tolerations helm values and then verify that the generated/rendered deployment template has  proper fields set.
Let me know if you need some help doing this.

**Comment by fabiomarinetti** [comment]
Hi @viveksinghggits, I took a look into the tests, I would like to launch helm install with --dry-run, anyway even though I understand how to pass this to the helmApp I don't get how/if it is used and what it is expected to return by the install function.
In fact in the helm/client.go I don't see any mention to dry-run param.
I am not very confident with go so it is probable I miss something.

**Comment by viveksinghggits** [comment]
Yeah, we would need to improve our helm client code as well to support `--dry-run` flag. we can either do that as part of this PR or another PR as well. And then we can incorporate that change in this PR.

I will discuss this in tomorrow's community call.

**Comment by hairyhum** [comment]
@fabiomarinetti in the meanwhile can you please provide a manual test plan while we're working on improving our test tools #2796

**Review by viveksinghggits — APPROVED** [review]

**Pull request merged**
