### PR TITLE
Upgrade kafka component version to 3.2.0

### LINKED ISSUE #1842: [BUG] Kafka version outdated
**Describe the bug**
Defined Kafka version in Cluster example creation [file](examples/kafka/adobe-s3-connector/kafka-cluster.yaml) is outdated.
Strimzi Kafka Operator accepts versions from 3.2.0.

**To Reproduce**
1. Apply [kafka-cluster.yml](examples/kafka/adobe-s3-connector/kafka-cluster.yaml) to Kubernetes Cluster
2. Java null pointer exception -> `UnsupportedKafkaVersionException: Unsupported Kafka.spec.kafka.version: 3.1.0. Supported versions are: [3.2.0, 3.2.1, 3.2.3, 3.3.1]`

**Expected behavior**
Successful deployment of Kafka compontents via [kafka-cluster.yml](examples/kafka/adobe-s3-connector/kafka-cluster.yaml)

**Screenshots**

**Environment**
Kubernetes Version/Provider: 1.23
Storage Provider: ...
Cluster Size (#nodes): ...
Data Size: ...

### PR DESCRIPTION
**Pull request by bitstan-earthyfrodo**
## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [x] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test

## Issues 

- fixes #1842 

## Test Plan

- [x] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

Manually tested the changes 

[BACKUP logs](https://gist.github.com/akankshakumari393/54eb6a81cf80b4e2d23e1f3c8698e46b)

[RESTORE logs](https://gist.github.com/akankshakumari393/2852274d71f790c318e13b7fc0627264)

### CODE REVIEW

**Comment by pavannd1** [comment]
@bitstan-earthyfrodo Thank you for trying out Kanister and for submitting this pull request 🎉.
Were you able to verify the backup/restore process on this new version?

**Comment by bitstan-earthyfrodo** [comment]
> @bitstan-earthyfrodo Thank you for trying out Kanister and for submitting this pull request 🎉. Were you able to verify the backup/restore process on this new version?

@pavannd1 I cannot use the blueprint in my setup because I'm having no Amazon S3 in place. In this case, I cannot test the backup/restore procedure but the current version in the [kafka-cluster.yml](examples/kafka/adobe-s3-connector/kafka-cluster.yaml) will definitly not work anymore with strimzi-kafka-operator in Helm v0.32.0(latest as of today).

**Comment by pavannd1** [comment]
Thank you @bitstan-earthyfrodo!
@akankshakumari393 Could you please help out with testing these changes?

**Comment by akankshakumari393** [comment]
sure will take a look. Thanks 👍🏻

**Comment by akankshakumari393** [comment]
Tried testing this and the zookeeper component is failing. Will investigate if there are some other changes that are required.

**Review by akankshakumari393 — APPROVED** [review]
Hey @bitstan-earthyfrodo, Thank you for raising, I have verified your changes on S3. Its works fine as described in our [example](https://github.com/kanisterio/kanister/blob/a8ef704c8bb5fa937a91048ee17b32e958e2b5ba/examples/kafka/adobe-s3-connector/README.md)

**Pull request merged**
