### PR TITLE
Adding kubeconfig as pre requisite in BUILD.md

### LINKED ISSUE #1543: [Docs] Specify K8s cluster requirement as a prerequisite for running tests
`make test` requires Kubernetes cluster config in the environment. Add this as a requirement in `BUILD.md`.

### PR DESCRIPTION
**Pull request by Sagar2366**
## Change Overview

Adding kubeconfig as pre requisite in BUILD.md

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [ ] :sunflower: Feature
- [x] :world_map: Documentation
- [ ] :robot: Test

## Issues 

- fixes #1543 

## Test Plan

- [ ] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

**Review by ihcsim — APPROVED** [review]

**Comment by ihcsim** [comment]
Don't worry about the CI failure. I thought I fixed that in #1642 - guess not!

**Comment by Sagar2366** [comment]
@ihcsim thank you.
Can you please add label to this PR "hactoberfest-accepted" ?

**Comment by ihcsim** [comment]
@Sagar2366 Done.

**Pull request merged**
